### PR TITLE
chore(java-dep-check): add GPL with CP exception

### PR DESCRIPTION
**Pull request by yanavasileva**
Update Stop and Go list with latest changes

### CODE REVIEW

**Comment by ThorbenLindhauer** [comment]
The name that the SBOM plugin generates will be `GPL-2.0-with-classpath-exception`. Here you can find how it maps the declared license name to a canonical name: https://github.com/CycloneDX/cyclonedx-core-java/blob/master/src/main/resources/license-mapping.json

**Comment by ThorbenLindhauer** [comment]
Please note that Tassilo and I discussed that we wanted to clarify with Uli if GPL with classpath exception should really be on the Go list or rather on the Caution list (because it has this additional condition "if used in compiled code" in Confluence and if it's on the Go list, engineers might just skip over it regardless how we use it). Maybe you can assign Tassilo for review so he can make sure this is clarified first.

**Comment by yanavasileva** [comment]
assigning @tasso94 for review
TODO:
- [ ]  clarify in which list the GPL with CP exception should belong

**Comment by tasso94** [comment]
Hi @yanavasileva, 

I reached out to Legal to clarify this. I'll keep you in the loop.

Best,
Tassilo

**Comment by tasso94** [comment]
Hi @yanavasileva,

The legal team moved the GPL/CL license from Go to Caution. Can you reflect that in your PR?
Cf. https://confluence.camunda.com/pages/viewpage.action?pageId=98605302

Best,
Tassilo

**Review by tasso94 — APPROVED** [review]
Looks good to me. 👍 

Have you tested it?

**Comment by yanavasileva** [comment]
Tested here: https://github.com/camunda/camunda-bpm-platform/pull/3904, the license (e.g.: `jersey-client`) is marked with ⚠ as expected.
Therefore merging the change.

**Pull request merged**
